export const inspections = [
    {
        "zctiP_ID": 1286,
        "zctiP_Partner_ID": null,
        "zctiP_Partner_ID_Desc": "",
        "zctiP_Batch_Number": "Batch-30072024S",
        "zctiP_Part_Template_ID": 121,
        "zctiP_Status": "SAVED",
        "zctiP_Insp_Type": null,
        "zctiP_Insp_Type_Desc": "",
        "zctiP_Operation_ID": 29,
        "zctiP_Operation_ID_Desc": "OP10",
        "zctiP_Insp_Type_Opr_Flag": 2,
        "zctiP_Lot_Size": 50,
        "zctiP_Reject_Revision_Number": 0,
        "zctiP_PO_Number": "",
        "zctiP_Hit_Number": "",
        "zctiP_SPC_Machine": "",
        "zctiP_Sample_Rule_ID": null,
        "zctiP_Parent_Inspection_ID": null,
        "zctiP_Created_By": 40,
        "zctiP_Created_By_Desc": "Nikhil Sarode",
        "zctiP_Created_On": "2024-07-30T10:34:19",
        "zctiP_Submitted_By": null,
        "zctiP_Submitted_By_Desc": null,
        "zctiP_Submitted_On": null,
        "zctiP_Verified_By": null,
        "zctiP_Verified_By_Desc": "",
        "zctiP_Verified_On": null,
        "zctiP_Verified_Comment": "",
        "zctppT_Label": "Test-19072024 [ 5 ] ",
        "zctppT_Part_Template_Desc": null,
        "zctiP_Inspection_Plan_ids": null,
        "zctiP_Filled_Values_Per": 2.78,
        "zctiP_Filled_Values_Ok_Per": 0,
        "zctiP_Mode": -1,
        "zctiP_Measurement_Move_mode": -1,
        "zctiP_Verified_On_From": null,
        "zctiP_Verified_On_To": null,
        "zctiP_ZCTPPT_Template_Type": null,
        "zctiP_ZCTPPT_Template_Code": "Manufacturing"
    },
    {
        "zctiP_ID": 1285,
        "zctiP_Partner_ID": null,
        "zctiP_Partner_ID_Desc": "",
        "zctiP_Batch_Number": "Batch-30072024",
        "zctiP_Part_Template_ID": 121,
        "zctiP_Status": "SAVED",
        "zctiP_Insp_Type": null,
        "zctiP_Insp_Type_Desc": "",
        "zctiP_Operation_ID": 29,
        "zctiP_Operation_ID_Desc": "OP10",
        "zctiP_Insp_Type_Opr_Flag": 2,
        "zctiP_Lot_Size": 100,
        "zctiP_Reject_Revision_Number": 0,
        "zctiP_PO_Number": "",
        "zctiP_Hit_Number": "",
        "zctiP_SPC_Machine": "",
        "zctiP_Sample_Rule_ID": null,
        "zctiP_Parent_Inspection_ID": null,
        "zctiP_Created_By": 40,
        "zctiP_Created_By_Desc": "Nikhil Sarode",
        "zctiP_Created_On": "2024-07-30T10:31:01",
        "zctiP_Submitted_By": null,
        "zctiP_Submitted_By_Desc": null,
        "zctiP_Submitted_On": null,
        "zctiP_Verified_By": null,
        "zctiP_Verified_By_Desc": "",
        "zctiP_Verified_On": null,
        "zctiP_Verified_Comment": "",
        "zctppT_Label": "Test-19072024 [ 5 ] ",
        "zctppT_Part_Template_Desc": null,
        "zctiP_Inspection_Plan_ids": null,
        "zctiP_Filled_Values_Per": 0,
        "zctiP_Filled_Values_Ok_Per": 0,
        "zctiP_Mode": -1,
        "zctiP_Measurement_Move_mode": -1,
        "zctiP_Verified_On_From": null,
        "zctiP_Verified_On_To": null,
        "zctiP_ZCTPPT_Template_Type": null,
        "zctiP_ZCTPPT_Template_Code": "Manufacturing"
    },
    {
        "zctiP_ID": 284,
        "zctiP_Partner_ID": null,
        "zctiP_Partner_ID_Desc": "",
        "zctiP_Batch_Number": "Batch-26072024-2",
        "zctiP_Part_Template_ID": 121,
        "zctiP_Status": "SAVED",
        "zctiP_Insp_Type": null,
        "zctiP_Insp_Type_Desc": "",
        "zctiP_Operation_ID": 29,
        "zctiP_Operation_ID_Desc": "OP10",
        "zctiP_Insp_Type_Opr_Flag": 2,
        "zctiP_Lot_Size": 10,
        "zctiP_Reject_Revision_Number": 0,
        "zctiP_PO_Number": "",
        "zctiP_Hit_Number": "",
        "zctiP_SPC_Machine": "",
        "zctiP_Sample_Rule_ID": null,
        "zctiP_Parent_Inspection_ID": null,
        "zctiP_Created_By": 40,
        "zctiP_Created_By_Desc": "Nikhil Sarode",
        "zctiP_Created_On": "2024-07-26T17:41:53",
        "zctiP_Submitted_By": null,
        "zctiP_Submitted_By_Desc": null,
        "zctiP_Submitted_On": null,
        "zctiP_Verified_By": null,
        "zctiP_Verified_By_Desc": "",
        "zctiP_Verified_On": null,
        "zctiP_Verified_Comment": "",
        "zctppT_Label": "Test-19072024 [ 5 ] ",
        "zctppT_Part_Template_Desc": null,
        "zctiP_Inspection_Plan_ids": null,
        "zctiP_Filled_Values_Per": 8.33,
        "zctiP_Filled_Values_Ok_Per": 100,
        "zctiP_Mode": -1,
        "zctiP_Measurement_Move_mode": -1,
        "zctiP_Verified_On_From": null,
        "zctiP_Verified_On_To": null,
        "zctiP_ZCTPPT_Template_Type": null,
        "zctiP_ZCTPPT_Template_Code": "Manufacturing"
    },
    {
        "zctiP_ID": 283,
        "zctiP_Partner_ID": null,
        "zctiP_Partner_ID_Desc": "",
        "zctiP_Batch_Number": "Batch-26072024",
        "zctiP_Part_Template_ID": 121,
        "zctiP_Status": "SAVED",
        "zctiP_Insp_Type": null,
        "zctiP_Insp_Type_Desc": "",
        "zctiP_Operation_ID": 29,
        "zctiP_Operation_ID_Desc": "OP10",
        "zctiP_Insp_Type_Opr_Flag": 2,
        "zctiP_Lot_Size": 10,
        "zctiP_Reject_Revision_Number": 0,
        "zctiP_PO_Number": "",
        "zctiP_Hit_Number": "",
        "zctiP_SPC_Machine": "",
        "zctiP_Sample_Rule_ID": null,
        "zctiP_Parent_Inspection_ID": null,
        "zctiP_Created_By": 40,
        "zctiP_Created_By_Desc": "Nikhil Sarode",
        "zctiP_Created_On": "2024-07-26T17:39:46",
        "zctiP_Submitted_By": null,
        "zctiP_Submitted_By_Desc": null,
        "zctiP_Submitted_On": null,
        "zctiP_Verified_By": null,
        "zctiP_Verified_By_Desc": "",
        "zctiP_Verified_On": null,
        "zctiP_Verified_Comment": "",
        "zctppT_Label": "Test-19072024 [ 5 ] ",
        "zctppT_Part_Template_Desc": null,
        "zctiP_Inspection_Plan_ids": null,
        "zctiP_Filled_Values_Per": 8.33,
        "zctiP_Filled_Values_Ok_Per": 0,
        "zctiP_Mode": -1,
        "zctiP_Measurement_Move_mode": -1,
        "zctiP_Verified_On_From": null,
        "zctiP_Verified_On_To": null,
        "zctiP_ZCTPPT_Template_Type": null,
        "zctiP_ZCTPPT_Template_Code": "Manufacturing"
    },
    {
        "zctiP_ID": 282,
        "zctiP_Partner_ID": null,
        "zctiP_Partner_ID_Desc": "",
        "zctiP_Batch_Number": "BATCH0055ws",
        "zctiP_Part_Template_ID": 114,
        "zctiP_Status": "SUBMITTED",
        "zctiP_Insp_Type": 3,
        "zctiP_Insp_Type_Desc": "Final",
        "zctiP_Operation_ID": null,
        "zctiP_Operation_ID_Desc": "",
        "zctiP_Insp_Type_Opr_Flag": 1,
        "zctiP_Lot_Size": 10,
        "zctiP_Reject_Revision_Number": 0,
        "zctiP_PO_Number": "",
        "zctiP_Hit_Number": "hit",
        "zctiP_SPC_Machine": "",
        "zctiP_Sample_Rule_ID": null,
        "zctiP_Parent_Inspection_ID": null,
        "zctiP_Created_By": 40,
        "zctiP_Created_By_Desc": "Nikhil Sarode",
        "zctiP_Created_On": "2024-07-25T15:15:14",
        "zctiP_Submitted_By": 40,
        "zctiP_Submitted_By_Desc": null,
        "zctiP_Submitted_On": "2024-07-26T16:56:34",
        "zctiP_Verified_By": null,
        "zctiP_Verified_By_Desc": "",
        "zctiP_Verified_On": null,
        "zctiP_Verified_Comment": "",
        "zctppT_Label": "543527 [ 8 ] ",
        "zctppT_Part_Template_Desc": null,
        "zctiP_Inspection_Plan_ids": null,
        "zctiP_Filled_Values_Per": 15.56,
        "zctiP_Filled_Values_Ok_Per": 14.29,
        "zctiP_Mode": -1,
        "zctiP_Measurement_Move_mode": -1,
        "zctiP_Verified_On_From": null,
        "zctiP_Verified_On_To": null,
        "zctiP_ZCTPPT_Template_Type": null,
        "zctiP_ZCTPPT_Template_Code": "Manufacturing"
    },
    {
        "zctiP_ID": 281,
        "zctiP_Partner_ID": null,
        "zctiP_Partner_ID_Desc": "",
        "zctiP_Batch_Number": "Batch- Test",
        "zctiP_Part_Template_ID": 108,
        "zctiP_Status": "SUBMITTED",
        "zctiP_Insp_Type": null,
        "zctiP_Insp_Type_Desc": "",
        "zctiP_Operation_ID": 30,
        "zctiP_Operation_ID_Desc": "Op20",
        "zctiP_Insp_Type_Opr_Flag": 2,
        "zctiP_Lot_Size": 50,
        "zctiP_Reject_Revision_Number": 0,
        "zctiP_PO_Number": "",
        "zctiP_Hit_Number": "",
        "zctiP_SPC_Machine": "",
        "zctiP_Sample_Rule_ID": null,
        "zctiP_Parent_Inspection_ID": null,
        "zctiP_Created_By": 40,
        "zctiP_Created_By_Desc": "Nikhil Sarode",
        "zctiP_Created_On": "2024-07-23T14:53:33",
        "zctiP_Submitted_By": 40,
        "zctiP_Submitted_By_Desc": null,
        "zctiP_Submitted_On": "2024-07-26T16:58:33",
        "zctiP_Verified_By": null,
        "zctiP_Verified_By_Desc": "",
        "zctiP_Verified_On": null,
        "zctiP_Verified_Comment": "",
        "zctppT_Label": "Test_15072024 [ 1 ] ",
        "zctppT_Part_Template_Desc": null,
        "zctiP_Inspection_Plan_ids": null,
        "zctiP_Filled_Values_Per": 20.93,
        "zctiP_Filled_Values_Ok_Per": 33.33,
        "zctiP_Mode": -1,
        "zctiP_Measurement_Move_mode": -1,
        "zctiP_Verified_On_From": null,
        "zctiP_Verified_On_To": null,
        "zctiP_ZCTPPT_Template_Type": null,
        "zctiP_ZCTPPT_Template_Code": "Receiving"
    },
    {
        "zctiP_ID": 280,
        "zctiP_Partner_ID": null,
        "zctiP_Partner_ID_Desc": "",
        "zctiP_Batch_Number": "Batch-16072024",
        "zctiP_Part_Template_ID": 108,
        "zctiP_Status": "SUBMITTED",
        "zctiP_Insp_Type": 2,
        "zctiP_Insp_Type_Desc": "In Progress",
        "zctiP_Operation_ID": null,
        "zctiP_Operation_ID_Desc": "",
        "zctiP_Insp_Type_Opr_Flag": 1,
        "zctiP_Lot_Size": 12,
        "zctiP_Reject_Revision_Number": 0,
        "zctiP_PO_Number": "",
        "zctiP_Hit_Number": "",
        "zctiP_SPC_Machine": "",
        "zctiP_Sample_Rule_ID": null,
        "zctiP_Parent_Inspection_ID": null,
        "zctiP_Created_By": 40,
        "zctiP_Created_By_Desc": "Nikhil Sarode",
        "zctiP_Created_On": "2024-07-23T14:52:50",
        "zctiP_Submitted_By": 40,
        "zctiP_Submitted_By_Desc": null,
        "zctiP_Submitted_On": "2024-07-26T17:01:31",
        "zctiP_Verified_By": null,
        "zctiP_Verified_By_Desc": "",
        "zctiP_Verified_On": null,
        "zctiP_Verified_Comment": "",
        "zctppT_Label": "Test_15072024 [ 1 ] ",
        "zctppT_Part_Template_Desc": null,
        "zctiP_Inspection_Plan_ids": null,
        "zctiP_Filled_Values_Per": 83.33,
        "zctiP_Filled_Values_Ok_Per": 100,
        "zctiP_Mode": -1,
        "zctiP_Measurement_Move_mode": -1,
        "zctiP_Verified_On_From": null,
        "zctiP_Verified_On_To": null,
        "zctiP_ZCTPPT_Template_Type": null,
        "zctiP_ZCTPPT_Template_Code": "Receiving"
    },
    {
        "zctiP_ID": 279,
        "zctiP_Partner_ID": null,
        "zctiP_Partner_ID_Desc": "",
        "zctiP_Batch_Number": "Batch-23072024",
        "zctiP_Part_Template_ID": 106,
        "zctiP_Status": "SUBMITTED",
        "zctiP_Insp_Type": null,
        "zctiP_Insp_Type_Desc": "",
        "zctiP_Operation_ID": 29,
        "zctiP_Operation_ID_Desc": "OP10",
        "zctiP_Insp_Type_Opr_Flag": 2,
        "zctiP_Lot_Size": 50,
        "zctiP_Reject_Revision_Number": 0,
        "zctiP_PO_Number": "",
        "zctiP_Hit_Number": "",
        "zctiP_SPC_Machine": "",
        "zctiP_Sample_Rule_ID": null,
        "zctiP_Parent_Inspection_ID": null,
        "zctiP_Created_By": 40,
        "zctiP_Created_By_Desc": "Nikhil Sarode",
        "zctiP_Created_On": "2024-07-23T14:44:42",
        "zctiP_Submitted_By": 40,
        "zctiP_Submitted_By_Desc": null,
        "zctiP_Submitted_On": "2024-07-26T17:02:44",
        "zctiP_Verified_By": null,
        "zctiP_Verified_By_Desc": "",
        "zctiP_Verified_On": null,
        "zctiP_Verified_Comment": "",
        "zctppT_Label": "Test-19072024 [ 1 ] ",
        "zctppT_Part_Template_Desc": null,
        "zctiP_Inspection_Plan_ids": null,
        "zctiP_Filled_Values_Per": 15.63,
        "zctiP_Filled_Values_Ok_Per": 53.33,
        "zctiP_Mode": -1,
        "zctiP_Measurement_Move_mode": -1,
        "zctiP_Verified_On_From": null,
        "zctiP_Verified_On_To": null,
        "zctiP_ZCTPPT_Template_Type": null,
        "zctiP_ZCTPPT_Template_Code": "Manufacturing"
    },
    {
        "zctiP_ID": 277,
        "zctiP_Partner_ID": null,
        "zctiP_Partner_ID_Desc": "",
        "zctiP_Batch_Number": "1234567876543",
        "zctiP_Part_Template_ID": 114,
        "zctiP_Status": "SUBMITTED",
        "zctiP_Insp_Type": 1,
        "zctiP_Insp_Type_Desc": "First Piece",
        "zctiP_Operation_ID": null,
        "zctiP_Operation_ID_Desc": "",
        "zctiP_Insp_Type_Opr_Flag": 1,
        "zctiP_Lot_Size": 234,
        "zctiP_Reject_Revision_Number": 0,
        "zctiP_PO_Number": "",
        "zctiP_Hit_Number": "",
        "zctiP_SPC_Machine": "",
        "zctiP_Sample_Rule_ID": null,
        "zctiP_Parent_Inspection_ID": null,
        "zctiP_Created_By": 40,
        "zctiP_Created_By_Desc": "Nikhil Sarode",
        "zctiP_Created_On": "2024-07-23T13:33:15",
        "zctiP_Submitted_By": 40,
        "zctiP_Submitted_By_Desc": null,
        "zctiP_Submitted_On": "2024-07-26T17:04:00",
        "zctiP_Verified_By": null,
        "zctiP_Verified_By_Desc": "",
        "zctiP_Verified_On": null,
        "zctiP_Verified_Comment": "",
        "zctppT_Label": "543527 [ 8 ] ",
        "zctppT_Part_Template_Desc": null,
        "zctiP_Inspection_Plan_ids": null,
        "zctiP_Filled_Values_Per": 88.89,
        "zctiP_Filled_Values_Ok_Per": 0,
        "zctiP_Mode": -1,
        "zctiP_Measurement_Move_mode": -1,
        "zctiP_Verified_On_From": null,
        "zctiP_Verified_On_To": null,
        "zctiP_ZCTPPT_Template_Type": null,
        "zctiP_ZCTPPT_Template_Code": "Manufacturing"
    },
    {
        "zctiP_ID": 276,
        "zctiP_Partner_ID": null,
        "zctiP_Partner_ID_Desc": "",
        "zctiP_Batch_Number": "Batch-1607202421312",
        "zctiP_Part_Template_ID": 114,
        "zctiP_Status": "SUBMITTED",
        "zctiP_Insp_Type": 1,
        "zctiP_Insp_Type_Desc": "First Piece",
        "zctiP_Operation_ID": null,
        "zctiP_Operation_ID_Desc": "",
        "zctiP_Insp_Type_Opr_Flag": 1,
        "zctiP_Lot_Size": 23,
        "zctiP_Reject_Revision_Number": 0,
        "zctiP_PO_Number": "",
        "zctiP_Hit_Number": "6515",
        "zctiP_SPC_Machine": "",
        "zctiP_Sample_Rule_ID": null,
        "zctiP_Parent_Inspection_ID": null,
        "zctiP_Created_By": 40,
        "zctiP_Created_By_Desc": "Nikhil Sarode",
        "zctiP_Created_On": "2024-07-23T13:29:55",
        "zctiP_Submitted_By": 40,
        "zctiP_Submitted_By_Desc": null,
        "zctiP_Submitted_On": "2024-07-26T17:04:07",
        "zctiP_Verified_By": null,
        "zctiP_Verified_By_Desc": "",
        "zctiP_Verified_On": null,
        "zctiP_Verified_Comment": "",
        "zctppT_Label": "543527 [ 8 ] ",
        "zctppT_Part_Template_Desc": null,
        "zctiP_Inspection_Plan_ids": null,
        "zctiP_Filled_Values_Per": 44.44,
        "zctiP_Filled_Values_Ok_Per": 0,
        "zctiP_Mode": -1,
        "zctiP_Measurement_Move_mode": -1,
        "zctiP_Verified_On_From": null,
        "zctiP_Verified_On_To": null,
        "zctiP_ZCTPPT_Template_Type": null,
        "zctiP_ZCTPPT_Template_Code": "Manufacturing"
    },
    {
        "zctiP_ID": 273,
        "zctiP_Partner_ID": null,
        "zctiP_Partner_ID_Desc": "",
        "zctiP_Batch_Number": "20_07_2024-1",
        "zctiP_Part_Template_ID": 110,
        "zctiP_Status": "SUBMITTED",
        "zctiP_Insp_Type": 1,
        "zctiP_Insp_Type_Desc": "First Piece",
        "zctiP_Operation_ID": null,
        "zctiP_Operation_ID_Desc": "",
        "zctiP_Insp_Type_Opr_Flag": 1,
        "zctiP_Lot_Size": 5,
        "zctiP_Reject_Revision_Number": 0,
        "zctiP_PO_Number": "",
        "zctiP_Hit_Number": "1",
        "zctiP_SPC_Machine": "",
        "zctiP_Sample_Rule_ID": null,
        "zctiP_Parent_Inspection_ID": null,
        "zctiP_Created_By": 40,
        "zctiP_Created_By_Desc": "Nikhil Sarode",
        "zctiP_Created_On": "2024-07-23T11:51:50",
        "zctiP_Submitted_By": 40,
        "zctiP_Submitted_By_Desc": null,
        "zctiP_Submitted_On": "2024-07-26T14:37:45",
        "zctiP_Verified_By": null,
        "zctiP_Verified_By_Desc": "",
        "zctiP_Verified_On": null,
        "zctiP_Verified_Comment": "",
        "zctppT_Label": "543527 [ 2 ] ",
        "zctppT_Part_Template_Desc": null,
        "zctiP_Inspection_Plan_ids": null,
        "zctiP_Filled_Values_Per": 90,
        "zctiP_Filled_Values_Ok_Per": 55.56,
        "zctiP_Mode": -1,
        "zctiP_Measurement_Move_mode": -1,
        "zctiP_Verified_On_From": null,
        "zctiP_Verified_On_To": null,
        "zctiP_ZCTPPT_Template_Type": null,
        "zctiP_ZCTPPT_Template_Code": "Manufacturing"
    },
    {
        "zctiP_ID": 272,
        "zctiP_Partner_ID": null,
        "zctiP_Partner_ID_Desc": "",
        "zctiP_Batch_Number": "Batch-22",
        "zctiP_Part_Template_ID": 106,
        "zctiP_Status": "SUBMITTED",
        "zctiP_Insp_Type": null,
        "zctiP_Insp_Type_Desc": "",
        "zctiP_Operation_ID": 29,
        "zctiP_Operation_ID_Desc": "OP10",
        "zctiP_Insp_Type_Opr_Flag": 2,
        "zctiP_Lot_Size": 50,
        "zctiP_Reject_Revision_Number": 0,
        "zctiP_PO_Number": "",
        "zctiP_Hit_Number": "H-22",
        "zctiP_SPC_Machine": "",
        "zctiP_Sample_Rule_ID": null,
        "zctiP_Parent_Inspection_ID": null,
        "zctiP_Created_By": 40,
        "zctiP_Created_By_Desc": "Nikhil Sarode",
        "zctiP_Created_On": "2024-07-22T13:11:29",
        "zctiP_Submitted_By": 40,
        "zctiP_Submitted_By_Desc": null,
        "zctiP_Submitted_On": "2024-07-26T17:04:48",
        "zctiP_Verified_By": null,
        "zctiP_Verified_By_Desc": "",
        "zctiP_Verified_On": null,
        "zctiP_Verified_Comment": "",
        "zctppT_Label": "Test-19072024 [ 1 ] ",
        "zctppT_Part_Template_Desc": null,
        "zctiP_Inspection_Plan_ids": null,
        "zctiP_Filled_Values_Per": 15.63,
        "zctiP_Filled_Values_Ok_Per": 53.33,
        "zctiP_Mode": -1,
        "zctiP_Measurement_Move_mode": -1,
        "zctiP_Verified_On_From": null,
        "zctiP_Verified_On_To": null,
        "zctiP_ZCTPPT_Template_Type": null,
        "zctiP_ZCTPPT_Template_Code": "Manufacturing"
    },
    {
        "zctiP_ID": 270,
        "zctiP_Partner_ID": null,
        "zctiP_Partner_ID_Desc": "",
        "zctiP_Batch_Number": "BATCH40401",
        "zctiP_Part_Template_ID": 111,
        "zctiP_Status": "SAVED",
        "zctiP_Insp_Type": 3,
        "zctiP_Insp_Type_Desc": "Final",
        "zctiP_Operation_ID": null,
        "zctiP_Operation_ID_Desc": "",
        "zctiP_Insp_Type_Opr_Flag": 1,
        "zctiP_Lot_Size": 10,
        "zctiP_Reject_Revision_Number": 0,
        "zctiP_PO_Number": "",
        "zctiP_Hit_Number": "hit",
        "zctiP_SPC_Machine": "",
        "zctiP_Sample_Rule_ID": null,
        "zctiP_Parent_Inspection_ID": null,
        "zctiP_Created_By": null,
        "zctiP_Created_By_Desc": "",
        "zctiP_Created_On": "2024-07-22T12:24:44",
        "zctiP_Submitted_By": null,
        "zctiP_Submitted_By_Desc": null,
        "zctiP_Submitted_On": null,
        "zctiP_Verified_By": null,
        "zctiP_Verified_By_Desc": "",
        "zctiP_Verified_On": null,
        "zctiP_Verified_Comment": "",
        "zctppT_Label": "123 [ 4040 ] ",
        "zctppT_Part_Template_Desc": null,
        "zctiP_Inspection_Plan_ids": null,
        "zctiP_Filled_Values_Per": 100,
        "zctiP_Filled_Values_Ok_Per": 50,
        "zctiP_Mode": -1,
        "zctiP_Measurement_Move_mode": -1,
        "zctiP_Verified_On_From": null,
        "zctiP_Verified_On_To": null,
        "zctiP_ZCTPPT_Template_Type": null,
        "zctiP_ZCTPPT_Template_Code": "Manufacturing"
    },
    {
        "zctiP_ID": 269,
        "zctiP_Partner_ID": null,
        "zctiP_Partner_ID_Desc": "",
        "zctiP_Batch_Number": "BATCH4040",
        "zctiP_Part_Template_ID": 111,
        "zctiP_Status": "SAVED",
        "zctiP_Insp_Type": 3,
        "zctiP_Insp_Type_Desc": "Final",
        "zctiP_Operation_ID": null,
        "zctiP_Operation_ID_Desc": "",
        "zctiP_Insp_Type_Opr_Flag": 1,
        "zctiP_Lot_Size": 10,
        "zctiP_Reject_Revision_Number": 0,
        "zctiP_PO_Number": "",
        "zctiP_Hit_Number": "hit",
        "zctiP_SPC_Machine": "",
        "zctiP_Sample_Rule_ID": null,
        "zctiP_Parent_Inspection_ID": null,
        "zctiP_Created_By": null,
        "zctiP_Created_By_Desc": "",
        "zctiP_Created_On": "2024-07-22T12:12:48",
        "zctiP_Submitted_By": null,
        "zctiP_Submitted_By_Desc": null,
        "zctiP_Submitted_On": null,
        "zctiP_Verified_By": null,
        "zctiP_Verified_By_Desc": "",
        "zctiP_Verified_On": null,
        "zctiP_Verified_Comment": "",
        "zctppT_Label": "123 [ 4040 ] ",
        "zctppT_Part_Template_Desc": null,
        "zctiP_Inspection_Plan_ids": null,
        "zctiP_Filled_Values_Per": 100,
        "zctiP_Filled_Values_Ok_Per": 50,
        "zctiP_Mode": -1,
        "zctiP_Measurement_Move_mode": -1,
        "zctiP_Verified_On_From": null,
        "zctiP_Verified_On_To": null,
        "zctiP_ZCTPPT_Template_Type": null,
        "zctiP_ZCTPPT_Template_Code": "Manufacturing"
    },
    {
        "zctiP_ID": 268,
        "zctiP_Partner_ID": null,
        "zctiP_Partner_ID_Desc": "",
        "zctiP_Batch_Number": "16072024asxs",
        "zctiP_Part_Template_ID": 106,
        "zctiP_Status": "SUBMITTED",
        "zctiP_Insp_Type": 2,
        "zctiP_Insp_Type_Desc": "In Progress",
        "zctiP_Operation_ID": null,
        "zctiP_Operation_ID_Desc": "",
        "zctiP_Insp_Type_Opr_Flag": 1,
        "zctiP_Lot_Size": 12,
        "zctiP_Reject_Revision_Number": 0,
        "zctiP_PO_Number": "",
        "zctiP_Hit_Number": "32",
        "zctiP_SPC_Machine": "",
        "zctiP_Sample_Rule_ID": null,
        "zctiP_Parent_Inspection_ID": null,
        "zctiP_Created_By": 40,
        "zctiP_Created_By_Desc": "Nikhil Sarode",
        "zctiP_Created_On": "2024-07-22T11:56:55",
        "zctiP_Submitted_By": 40,
        "zctiP_Submitted_By_Desc": null,
        "zctiP_Submitted_On": "2024-07-22T11:59:49",
        "zctiP_Verified_By": null,
        "zctiP_Verified_By_Desc": "",
        "zctiP_Verified_On": null,
        "zctiP_Verified_Comment": "",
        "zctppT_Label": "Test-19072024 [ 1 ] ",
        "zctppT_Part_Template_Desc": null,
        "zctiP_Inspection_Plan_ids": null,
        "zctiP_Filled_Values_Per": 66.67,
        "zctiP_Filled_Values_Ok_Per": 100,
        "zctiP_Mode": -1,
        "zctiP_Measurement_Move_mode": -1,
        "zctiP_Verified_On_From": null,
        "zctiP_Verified_On_To": null,
        "zctiP_ZCTPPT_Template_Type": null,
        "zctiP_ZCTPPT_Template_Code": "Manufacturing"
    },
    {
        "zctiP_ID": 267,
        "zctiP_Partner_ID": null,
        "zctiP_Partner_ID_Desc": "",
        "zctiP_Batch_Number": "16072024111",
        "zctiP_Part_Template_ID": 106,
        "zctiP_Status": "SAVED",
        "zctiP_Insp_Type": 1,
        "zctiP_Insp_Type_Desc": "First Piece",
        "zctiP_Operation_ID": null,
        "zctiP_Operation_ID_Desc": "",
        "zctiP_Insp_Type_Opr_Flag": 1,
        "zctiP_Lot_Size": 12,
        "zctiP_Reject_Revision_Number": 0,
        "zctiP_PO_Number": "",
        "zctiP_Hit_Number": "H-100",
        "zctiP_SPC_Machine": "",
        "zctiP_Sample_Rule_ID": null,
        "zctiP_Parent_Inspection_ID": null,
        "zctiP_Created_By": null,
        "zctiP_Created_By_Desc": "",
        "zctiP_Created_On": "2024-07-22T11:54:49",
        "zctiP_Submitted_By": null,
        "zctiP_Submitted_By_Desc": null,
        "zctiP_Submitted_On": null,
        "zctiP_Verified_By": null,
        "zctiP_Verified_By_Desc": "",
        "zctiP_Verified_On": null,
        "zctiP_Verified_Comment": "",
        "zctppT_Label": "Test-19072024 [ 1 ] ",
        "zctppT_Part_Template_Desc": null,
        "zctiP_Inspection_Plan_ids": null,
        "zctiP_Filled_Values_Per": 75,
        "zctiP_Filled_Values_Ok_Per": 55.56,
        "zctiP_Mode": -1,
        "zctiP_Measurement_Move_mode": -1,
        "zctiP_Verified_On_From": null,
        "zctiP_Verified_On_To": null,
        "zctiP_ZCTPPT_Template_Type": null,
        "zctiP_ZCTPPT_Template_Code": "Manufacturing"
    },
    {
        "zctiP_ID": 266,
        "zctiP_Partner_ID": null,
        "zctiP_Partner_ID_Desc": "",
        "zctiP_Batch_Number": "21072024",
        "zctiP_Part_Template_ID": 106,
        "zctiP_Status": "SAVED",
        "zctiP_Insp_Type": 1,
        "zctiP_Insp_Type_Desc": "First Piece",
        "zctiP_Operation_ID": null,
        "zctiP_Operation_ID_Desc": "",
        "zctiP_Insp_Type_Opr_Flag": 1,
        "zctiP_Lot_Size": 10,
        "zctiP_Reject_Revision_Number": 0,
        "zctiP_PO_Number": "",
        "zctiP_Hit_Number": "12123",
        "zctiP_SPC_Machine": "",
        "zctiP_Sample_Rule_ID": null,
        "zctiP_Parent_Inspection_ID": null,
        "zctiP_Created_By": null,
        "zctiP_Created_By_Desc": "",
        "zctiP_Created_On": "2024-07-22T11:12:25",
        "zctiP_Submitted_By": null,
        "zctiP_Submitted_By_Desc": null,
        "zctiP_Submitted_On": null,
        "zctiP_Verified_By": null,
        "zctiP_Verified_By_Desc": "",
        "zctiP_Verified_On": null,
        "zctiP_Verified_Comment": "",
        "zctppT_Label": "Test-19072024 [ 1 ] ",
        "zctppT_Part_Template_Desc": null,
        "zctiP_Inspection_Plan_ids": null,
        "zctiP_Filled_Values_Per": 87.5,
        "zctiP_Filled_Values_Ok_Per": 64.29,
        "zctiP_Mode": -1,
        "zctiP_Measurement_Move_mode": -1,
        "zctiP_Verified_On_From": null,
        "zctiP_Verified_On_To": null,
        "zctiP_ZCTPPT_Template_Type": null,
        "zctiP_ZCTPPT_Template_Code": "Manufacturing"
    },
    {
        "zctiP_ID": 265,
        "zctiP_Partner_ID": null,
        "zctiP_Partner_ID_Desc": "",
        "zctiP_Batch_Number": "20_07_2024-2",
        "zctiP_Part_Template_ID": 110,
        "zctiP_Status": "SAVED",
        "zctiP_Insp_Type": null,
        "zctiP_Insp_Type_Desc": "",
        "zctiP_Operation_ID": 30,
        "zctiP_Operation_ID_Desc": "Op20",
        "zctiP_Insp_Type_Opr_Flag": 2,
        "zctiP_Lot_Size": 10,
        "zctiP_Reject_Revision_Number": 0,
        "zctiP_PO_Number": "",
        "zctiP_Hit_Number": "1",
        "zctiP_SPC_Machine": "",
        "zctiP_Sample_Rule_ID": null,
        "zctiP_Parent_Inspection_ID": null,
        "zctiP_Created_By": null,
        "zctiP_Created_By_Desc": "",
        "zctiP_Created_On": "2024-07-22T10:29:44",
        "zctiP_Submitted_By": null,
        "zctiP_Submitted_By_Desc": null,
        "zctiP_Submitted_On": null,
        "zctiP_Verified_By": null,
        "zctiP_Verified_By_Desc": "",
        "zctiP_Verified_On": null,
        "zctiP_Verified_Comment": "",
        "zctppT_Label": "543527 [ 2 ] ",
        "zctppT_Part_Template_Desc": null,
        "zctiP_Inspection_Plan_ids": null,
        "zctiP_Filled_Values_Per": 45,
        "zctiP_Filled_Values_Ok_Per": 37.04,
        "zctiP_Mode": -1,
        "zctiP_Measurement_Move_mode": -1,
        "zctiP_Verified_On_From": null,
        "zctiP_Verified_On_To": null,
        "zctiP_ZCTPPT_Template_Type": null,
        "zctiP_ZCTPPT_Template_Code": "Manufacturing"
    },
    {
        "zctiP_ID": 264,
        "zctiP_Partner_ID": null,
        "zctiP_Partner_ID_Desc": "",
        "zctiP_Batch_Number": "20_07_2024-3",
        "zctiP_Part_Template_ID": 110,
        "zctiP_Status": "SAVED",
        "zctiP_Insp_Type": null,
        "zctiP_Insp_Type_Desc": "",
        "zctiP_Operation_ID": 30,
        "zctiP_Operation_ID_Desc": "Op20",
        "zctiP_Insp_Type_Opr_Flag": 2,
        "zctiP_Lot_Size": 10,
        "zctiP_Reject_Revision_Number": 0,
        "zctiP_PO_Number": "",
        "zctiP_Hit_Number": "1",
        "zctiP_SPC_Machine": "",
        "zctiP_Sample_Rule_ID": null,
        "zctiP_Parent_Inspection_ID": null,
        "zctiP_Created_By": null,
        "zctiP_Created_By_Desc": "",
        "zctiP_Created_On": "2024-07-21T19:24:46",
        "zctiP_Submitted_By": null,
        "zctiP_Submitted_By_Desc": null,
        "zctiP_Submitted_On": null,
        "zctiP_Verified_By": null,
        "zctiP_Verified_By_Desc": "",
        "zctiP_Verified_On": null,
        "zctiP_Verified_Comment": "",
        "zctppT_Label": "543527 [ 2 ] ",
        "zctppT_Part_Template_Desc": null,
        "zctiP_Inspection_Plan_ids": null,
        "zctiP_Filled_Values_Per": 45,
        "zctiP_Filled_Values_Ok_Per": 37.04,
        "zctiP_Mode": -1,
        "zctiP_Measurement_Move_mode": -1,
        "zctiP_Verified_On_From": null,
        "zctiP_Verified_On_To": null,
        "zctiP_ZCTPPT_Template_Type": null,
        "zctiP_ZCTPPT_Template_Code": "Manufacturing"
    },
    {
        "zctiP_ID": 262,
        "zctiP_Partner_ID": null,
        "zctiP_Partner_ID_Desc": "",
        "zctiP_Batch_Number": "BATCH0066-156",
        "zctiP_Part_Template_ID": 110,
        "zctiP_Status": "SAVED",
        "zctiP_Insp_Type": 3,
        "zctiP_Insp_Type_Desc": "Final",
        "zctiP_Operation_ID": null,
        "zctiP_Operation_ID_Desc": "",
        "zctiP_Insp_Type_Opr_Flag": 1,
        "zctiP_Lot_Size": 10,
        "zctiP_Reject_Revision_Number": 1,
        "zctiP_PO_Number": "",
        "zctiP_Hit_Number": "hit",
        "zctiP_SPC_Machine": "",
        "zctiP_Sample_Rule_ID": null,
        "zctiP_Parent_Inspection_ID": 261,
        "zctiP_Created_By": 40,
        "zctiP_Created_By_Desc": "Nikhil Sarode",
        "zctiP_Created_On": "2024-07-21T11:29:21",
        "zctiP_Submitted_By": null,
        "zctiP_Submitted_By_Desc": null,
        "zctiP_Submitted_On": null,
        "zctiP_Verified_By": null,
        "zctiP_Verified_By_Desc": "",
        "zctiP_Verified_On": null,
        "zctiP_Verified_Comment": "",
        "zctppT_Label": "543527 [ 2 ] ",
        "zctppT_Part_Template_Desc": null,
        "zctiP_Inspection_Plan_ids": null,
        "zctiP_Filled_Values_Per": 100,
        "zctiP_Filled_Values_Ok_Per": 14.29,
        "zctiP_Mode": -1,
        "zctiP_Measurement_Move_mode": -1,
        "zctiP_Verified_On_From": null,
        "zctiP_Verified_On_To": null,
        "zctiP_ZCTPPT_Template_Type": null,
        "zctiP_ZCTPPT_Template_Code": "Manufacturing"
    },
    {
        "zctiP_ID": 260,
        "zctiP_Partner_ID": null,
        "zctiP_Partner_ID_Desc": "",
        "zctiP_Batch_Number": "hgt58",
        "zctiP_Part_Template_ID": 109,
        "zctiP_Status": "SAVED",
        "zctiP_Insp_Type": 1,
        "zctiP_Insp_Type_Desc": "First Piece",
        "zctiP_Operation_ID": null,
        "zctiP_Operation_ID_Desc": "",
        "zctiP_Insp_Type_Opr_Flag": 1,
        "zctiP_Lot_Size": 100,
        "zctiP_Reject_Revision_Number": 0,
        "zctiP_PO_Number": "",
        "zctiP_Hit_Number": "10",
        "zctiP_SPC_Machine": "",
        "zctiP_Sample_Rule_ID": null,
        "zctiP_Parent_Inspection_ID": null,
        "zctiP_Created_By": null,
        "zctiP_Created_By_Desc": "",
        "zctiP_Created_On": "2024-07-21T01:13:59",
        "zctiP_Submitted_By": null,
        "zctiP_Submitted_By_Desc": null,
        "zctiP_Submitted_On": null,
        "zctiP_Verified_By": null,
        "zctiP_Verified_By_Desc": "",
        "zctiP_Verified_On": null,
        "zctiP_Verified_Comment": "",
        "zctppT_Label": "123 [ 23 ] ",
        "zctppT_Part_Template_Desc": null,
        "zctiP_Inspection_Plan_ids": null,
        "zctiP_Filled_Values_Per": 8.16,
        "zctiP_Filled_Values_Ok_Per": 37.5,
        "zctiP_Mode": -1,
        "zctiP_Measurement_Move_mode": -1,
        "zctiP_Verified_On_From": null,
        "zctiP_Verified_On_To": null,
        "zctiP_ZCTPPT_Template_Type": null,
        "zctiP_ZCTPPT_Template_Code": "Manufacturing"
    },
    {
        "zctiP_ID": 258,
        "zctiP_Partner_ID": null,
        "zctiP_Partner_ID_Desc": "",
        "zctiP_Batch_Number": "20_07_2024_1",
        "zctiP_Part_Template_ID": 110,
        "zctiP_Status": "SAVED",
        "zctiP_Insp_Type": 3,
        "zctiP_Insp_Type_Desc": "Final",
        "zctiP_Operation_ID": null,
        "zctiP_Operation_ID_Desc": "",
        "zctiP_Insp_Type_Opr_Flag": 1,
        "zctiP_Lot_Size": 20,
        "zctiP_Reject_Revision_Number": 0,
        "zctiP_PO_Number": "",
        "zctiP_Hit_Number": "1",
        "zctiP_SPC_Machine": "",
        "zctiP_Sample_Rule_ID": null,
        "zctiP_Parent_Inspection_ID": null,
        "zctiP_Created_By": null,
        "zctiP_Created_By_Desc": "",
        "zctiP_Created_On": "2024-07-20T20:52:51",
        "zctiP_Submitted_By": null,
        "zctiP_Submitted_By_Desc": null,
        "zctiP_Submitted_On": null,
        "zctiP_Verified_By": null,
        "zctiP_Verified_By_Desc": "",
        "zctiP_Verified_On": null,
        "zctiP_Verified_Comment": "",
        "zctppT_Label": "543527 [ 2 ] ",
        "zctppT_Part_Template_Desc": null,
        "zctiP_Inspection_Plan_ids": null,
        "zctiP_Filled_Values_Per": 100,
        "zctiP_Filled_Values_Ok_Per": 14.29,
        "zctiP_Mode": -1,
        "zctiP_Measurement_Move_mode": -1,
        "zctiP_Verified_On_From": null,
        "zctiP_Verified_On_To": null,
        "zctiP_ZCTPPT_Template_Type": null,
        "zctiP_ZCTPPT_Template_Code": "Manufacturing"
    },
    {
        "zctiP_ID": 257,
        "zctiP_Partner_ID": null,
        "zctiP_Partner_ID_Desc": "",
        "zctiP_Batch_Number": "20_07_2024",
        "zctiP_Part_Template_ID": 110,
        "zctiP_Status": "SAVED",
        "zctiP_Insp_Type": 3,
        "zctiP_Insp_Type_Desc": "Final",
        "zctiP_Operation_ID": null,
        "zctiP_Operation_ID_Desc": "",
        "zctiP_Insp_Type_Opr_Flag": 1,
        "zctiP_Lot_Size": 20,
        "zctiP_Reject_Revision_Number": 0,
        "zctiP_PO_Number": "",
        "zctiP_Hit_Number": "1",
        "zctiP_SPC_Machine": "",
        "zctiP_Sample_Rule_ID": null,
        "zctiP_Parent_Inspection_ID": null,
        "zctiP_Created_By": null,
        "zctiP_Created_By_Desc": "",
        "zctiP_Created_On": "2024-07-20T19:00:38",
        "zctiP_Submitted_By": null,
        "zctiP_Submitted_By_Desc": null,
        "zctiP_Submitted_On": null,
        "zctiP_Verified_By": null,
        "zctiP_Verified_By_Desc": "",
        "zctiP_Verified_On": null,
        "zctiP_Verified_Comment": "",
        "zctppT_Label": "543527 [ 2 ] ",
        "zctppT_Part_Template_Desc": null,
        "zctiP_Inspection_Plan_ids": null,
        "zctiP_Filled_Values_Per": 100,
        "zctiP_Filled_Values_Ok_Per": 14.29,
        "zctiP_Mode": -1,
        "zctiP_Measurement_Move_mode": -1,
        "zctiP_Verified_On_From": null,
        "zctiP_Verified_On_To": null,
        "zctiP_ZCTPPT_Template_Type": null,
        "zctiP_ZCTPPT_Template_Code": "Manufacturing"
    },
    {
        "zctiP_ID": 256,
        "zctiP_Partner_ID": null,
        "zctiP_Partner_ID_Desc": "",
        "zctiP_Batch_Number": "20072024",
        "zctiP_Part_Template_ID": 106,
        "zctiP_Status": "SAVED",
        "zctiP_Insp_Type": 2,
        "zctiP_Insp_Type_Desc": "In Progress",
        "zctiP_Operation_ID": null,
        "zctiP_Operation_ID_Desc": "",
        "zctiP_Insp_Type_Opr_Flag": 1,
        "zctiP_Lot_Size": 10,
        "zctiP_Reject_Revision_Number": 0,
        "zctiP_PO_Number": "",
        "zctiP_Hit_Number": "500",
        "zctiP_SPC_Machine": "",
        "zctiP_Sample_Rule_ID": null,
        "zctiP_Parent_Inspection_ID": null,
        "zctiP_Created_By": null,
        "zctiP_Created_By_Desc": "",
        "zctiP_Created_On": "2024-07-20T18:00:25",
        "zctiP_Submitted_By": null,
        "zctiP_Submitted_By_Desc": null,
        "zctiP_Submitted_On": null,
        "zctiP_Verified_By": null,
        "zctiP_Verified_By_Desc": "",
        "zctiP_Verified_On": null,
        "zctiP_Verified_Comment": "",
        "zctppT_Label": "Test-19072024 [ 1 ] ",
        "zctppT_Part_Template_Desc": null,
        "zctiP_Inspection_Plan_ids": null,
        "zctiP_Filled_Values_Per": 100,
        "zctiP_Filled_Values_Ok_Per": 100,
        "zctiP_Mode": -1,
        "zctiP_Measurement_Move_mode": -1,
        "zctiP_Verified_On_From": null,
        "zctiP_Verified_On_To": null,
        "zctiP_ZCTPPT_Template_Type": null,
        "zctiP_ZCTPPT_Template_Code": "Manufacturing"
    },
    {
        "zctiP_ID": 255,
        "zctiP_Partner_ID": null,
        "zctiP_Partner_ID_Desc": "",
        "zctiP_Batch_Number": "BATCH00WSL",
        "zctiP_Part_Template_ID": 107,
        "zctiP_Status": "SAVED",
        "zctiP_Insp_Type": 2,
        "zctiP_Insp_Type_Desc": "In Progress",
        "zctiP_Operation_ID": null,
        "zctiP_Operation_ID_Desc": "",
        "zctiP_Insp_Type_Opr_Flag": 1,
        "zctiP_Lot_Size": 10,
        "zctiP_Reject_Revision_Number": 2,
        "zctiP_PO_Number": "",
        "zctiP_Hit_Number": "123",
        "zctiP_SPC_Machine": "",
        "zctiP_Sample_Rule_ID": null,
        "zctiP_Parent_Inspection_ID": 252,
        "zctiP_Created_By": 40,
        "zctiP_Created_By_Desc": "Nikhil Sarode",
        "zctiP_Created_On": "2024-07-19T19:01:47",
        "zctiP_Submitted_By": null,
        "zctiP_Submitted_By_Desc": null,
        "zctiP_Submitted_On": null,
        "zctiP_Verified_By": null,
        "zctiP_Verified_By_Desc": "",
        "zctiP_Verified_On": null,
        "zctiP_Verified_Comment": "",
        "zctppT_Label": "123 [ 111 ] ",
        "zctppT_Part_Template_Desc": null,
        "zctiP_Inspection_Plan_ids": null,
        "zctiP_Filled_Values_Per": 100,
        "zctiP_Filled_Values_Ok_Per": 50,
        "zctiP_Mode": -1,
        "zctiP_Measurement_Move_mode": -1,
        "zctiP_Verified_On_From": null,
        "zctiP_Verified_On_To": null,
        "zctiP_ZCTPPT_Template_Type": null,
        "zctiP_ZCTPPT_Template_Code": "Manufacturing"
    },
    {
        "zctiP_ID": 243,
        "zctiP_Partner_ID": null,
        "zctiP_Partner_ID_Desc": "",
        "zctiP_Batch_Number": "BATCH0055",
        "zctiP_Part_Template_ID": 107,
        "zctiP_Status": "SUBMITTED",
        "zctiP_Insp_Type": 2,
        "zctiP_Insp_Type_Desc": "In Progress",
        "zctiP_Operation_ID": null,
        "zctiP_Operation_ID_Desc": "",
        "zctiP_Insp_Type_Opr_Flag": 1,
        "zctiP_Lot_Size": 10,
        "zctiP_Reject_Revision_Number": 5,
        "zctiP_PO_Number": "",
        "zctiP_Hit_Number": "102",
        "zctiP_SPC_Machine": "",
        "zctiP_Sample_Rule_ID": null,
        "zctiP_Parent_Inspection_ID": 242,
        "zctiP_Created_By": 40,
        "zctiP_Created_By_Desc": "Nikhil Sarode",
        "zctiP_Created_On": "2024-07-19T17:01:16",
        "zctiP_Submitted_By": null,
        "zctiP_Submitted_By_Desc": null,
        "zctiP_Submitted_On": "2024-07-19T18:53:27",
        "zctiP_Verified_By": null,
        "zctiP_Verified_By_Desc": "",
        "zctiP_Verified_On": null,
        "zctiP_Verified_Comment": "",
        "zctppT_Label": "123 [ 111 ] ",
        "zctppT_Part_Template_Desc": null,
        "zctiP_Inspection_Plan_ids": null,
        "zctiP_Filled_Values_Per": 100,
        "zctiP_Filled_Values_Ok_Per": 50,
        "zctiP_Mode": -1,
        "zctiP_Measurement_Move_mode": -1,
        "zctiP_Verified_On_From": null,
        "zctiP_Verified_On_To": null,
        "zctiP_ZCTPPT_Template_Type": null,
        "zctiP_ZCTPPT_Template_Code": "Manufacturing"
    },
    {
        "zctiP_ID": 241,
        "zctiP_Partner_ID": null,
        "zctiP_Partner_ID_Desc": "",
        "zctiP_Batch_Number": "BATCH0055",
        "zctiP_Part_Template_ID": 107,
        "zctiP_Status": "SAVED",
        "zctiP_Insp_Type": 2,
        "zctiP_Insp_Type_Desc": "In Progress",
        "zctiP_Operation_ID": null,
        "zctiP_Operation_ID_Desc": "",
        "zctiP_Insp_Type_Opr_Flag": 1,
        "zctiP_Lot_Size": 10,
        "zctiP_Reject_Revision_Number": 3,
        "zctiP_PO_Number": "",
        "zctiP_Hit_Number": "102",
        "zctiP_SPC_Machine": "",
        "zctiP_Sample_Rule_ID": null,
        "zctiP_Parent_Inspection_ID": 240,
        "zctiP_Created_By": 40,
        "zctiP_Created_By_Desc": "Nikhil Sarode",
        "zctiP_Created_On": "2024-07-19T16:53:53",
        "zctiP_Submitted_By": null,
        "zctiP_Submitted_By_Desc": null,
        "zctiP_Submitted_On": null,
        "zctiP_Verified_By": null,
        "zctiP_Verified_By_Desc": "",
        "zctiP_Verified_On": null,
        "zctiP_Verified_Comment": "",
        "zctppT_Label": "123 [ 111 ] ",
        "zctppT_Part_Template_Desc": null,
        "zctiP_Inspection_Plan_ids": null,
        "zctiP_Filled_Values_Per": 100,
        "zctiP_Filled_Values_Ok_Per": 50,
        "zctiP_Mode": -1,
        "zctiP_Measurement_Move_mode": -1,
        "zctiP_Verified_On_From": null,
        "zctiP_Verified_On_To": null,
        "zctiP_ZCTPPT_Template_Type": null,
        "zctiP_ZCTPPT_Template_Code": "Manufacturing"
    },
    {
        "zctiP_ID": 235,
        "zctiP_Partner_ID": null,
        "zctiP_Partner_ID_Desc": "",
        "zctiP_Batch_Number": "HGT14",
        "zctiP_Part_Template_ID": 107,
        "zctiP_Status": "SAVED",
        "zctiP_Insp_Type": 2,
        "zctiP_Insp_Type_Desc": "In Progress",
        "zctiP_Operation_ID": null,
        "zctiP_Operation_ID_Desc": "",
        "zctiP_Insp_Type_Opr_Flag": 1,
        "zctiP_Lot_Size": 1000,
        "zctiP_Reject_Revision_Number": 0,
        "zctiP_PO_Number": "",
        "zctiP_Hit_Number": "20",
        "zctiP_SPC_Machine": "",
        "zctiP_Sample_Rule_ID": null,
        "zctiP_Parent_Inspection_ID": null,
        "zctiP_Created_By": null,
        "zctiP_Created_By_Desc": "",
        "zctiP_Created_On": "2024-07-19T16:20:25",
        "zctiP_Submitted_By": null,
        "zctiP_Submitted_By_Desc": null,
        "zctiP_Submitted_On": null,
        "zctiP_Verified_By": null,
        "zctiP_Verified_By_Desc": "",
        "zctiP_Verified_On": null,
        "zctiP_Verified_Comment": "",
        "zctppT_Label": "123 [ 111 ] ",
        "zctppT_Part_Template_Desc": null,
        "zctiP_Inspection_Plan_ids": null,
        "zctiP_Filled_Values_Per": 100,
        "zctiP_Filled_Values_Ok_Per": 50,
        "zctiP_Mode": -1,
        "zctiP_Measurement_Move_mode": -1,
        "zctiP_Verified_On_From": null,
        "zctiP_Verified_On_To": null,
        "zctiP_ZCTPPT_Template_Type": null,
        "zctiP_ZCTPPT_Template_Code": "Manufacturing"
    }
]